<Images>
	
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height

		padding: 50
		spacing: 20

		Image:
			id: color_type
			#source: 'images/green.png'
			#allow_stretch: True
			#keep_ratio: False

		#Image:
		#	id: yellow
		#	source: 'images/yellow.png'
		#	allow_stretch: True
		#	keep_ratio: False

		#Image:
		#	id: red
		#	source: 'images/red.jpg'
		#	allow_stretch: True
		#	keep_ratio: False '''